// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gukuivmhahwjwvekpbbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1a3Vpdm1oYWh3and2ZWtwYmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTg2NDAsImV4cCI6MjA1MjUzNDY0MH0.8cDF9165OwiPf2jbTXx1Kc3patAqxcMoAV5BTNfSoUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);